[package]
name = "sct_back_end"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
tokio = { version = "1.33.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tower-http = { version = "0.6.6", features = ["cors", "trace"] }
tracing-subscriber = "0.3.19"
tracing = "0.1.41"
dotenv = "0.15.0"
config = "0.15.16"
futures = "0.3"
reqwest = "0.12"
scraper = "0.23.1"

[build-dependencies]
prettyplease = "0.2.36"
openapiv3 = "2.2.0"
syn = "2.0.104"
progenitor = "0.11.0"
serde_yml = "0.0.12"
reqwest = { version = "0.12", features = ["json", "stream"] }
progenitor-client = "0.11.0"
indexmap = "2.10.0"
